/*
 * generated by Xtext 2.21.0
 */
package br.ufes.nemo.ledzeppllin.blackdog.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BlackDogUiModule extends AbstractBlackDogUiModule {

	public BlackDogUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
