/**
 * generated by Xtext 2.21.0
 */
package br.ufes.nemo.ledzeppllin.blackdog.blackDog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.nemo.ledzeppllin.blackdog.blackDog.BlackDogPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
