/**
 * generated by Xtext 2.21.0
 */
package br.ufes.nemo.ledzeppllin.blackdog.blackDog;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.nemo.ledzeppllin.blackdog.blackDog.Entity#getDescription <em>Description</em>}</li>
 *   <li>{@link br.ufes.nemo.ledzeppllin.blackdog.blackDog.Entity#getAnnotations <em>Annotations</em>}</li>
 *   <li>{@link br.ufes.nemo.ledzeppllin.blackdog.blackDog.Entity#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link br.ufes.nemo.ledzeppllin.blackdog.blackDog.Entity#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see br.ufes.nemo.ledzeppllin.blackdog.blackDog.BlackDogPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends Type
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference.
   * @see #setDescription(Description)
   * @see br.ufes.nemo.ledzeppllin.blackdog.blackDog.BlackDogPackage#getEntity_Description()
   * @model containment="true"
   * @generated
   */
  Description getDescription();

  /**
   * Sets the value of the '{@link br.ufes.nemo.ledzeppllin.blackdog.blackDog.Entity#getDescription <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' containment reference.
   * @see #getDescription()
   * @generated
   */
  void setDescription(Description value);

  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.nemo.ledzeppllin.blackdog.blackDog.Annotation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see br.ufes.nemo.ledzeppllin.blackdog.blackDog.BlackDogPackage#getEntity_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<Annotation> getAnnotations();

  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(Entity)
   * @see br.ufes.nemo.ledzeppllin.blackdog.blackDog.BlackDogPackage#getEntity_SuperType()
   * @model
   * @generated
   */
  Entity getSuperType();

  /**
   * Sets the value of the '{@link br.ufes.nemo.ledzeppllin.blackdog.blackDog.Entity#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(Entity value);

  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.nemo.ledzeppllin.blackdog.blackDog.Feature}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see br.ufes.nemo.ledzeppllin.blackdog.blackDog.BlackDogPackage#getEntity_Features()
   * @model containment="true"
   * @generated
   */
  EList<Feature> getFeatures();

} // Entity
