/*
 * generated by Xtext 2.21.0
 */
package br.ufes.nemo.ledzeppllin.blackdog;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BlackDogStandaloneSetup extends BlackDogStandaloneSetupGenerated {

	public static void doSetup() {
		new BlackDogStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
