/*
 * generated by Xtext 2.21.0
 */
package br.ufes.nemo.ledzeppllin.blackdog.ide;


/**
 * Use this class to register ide components.
 */
public class BlackDogIdeModule extends AbstractBlackDogIdeModule {
}
