/*
 * generated by Xtext 2.21.0
 */
package br.ufes.nemo.ledzeppllin.blackdog.parser.antlr;

import br.ufes.nemo.ledzeppllin.blackdog.parser.antlr.internal.InternalBlackDogParser;
import br.ufes.nemo.ledzeppllin.blackdog.services.BlackDogGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BlackDogParser extends AbstractAntlrParser {

	@Inject
	private BlackDogGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBlackDogParser createParser(XtextTokenStream stream) {
		return new InternalBlackDogParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public BlackDogGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BlackDogGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
